name: motatawera
description: Attendance application for students.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
 
  flutter:
    sdk: flutter 
  flutter_localizations:   
    sdk: flutter
    
    
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  carousel_pro: ^1.0.0
  http: ^0.13.1
  splashscreen: ^1.3.5
  qr_code_scanner: ^0.7.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  gradient_widgets: ^0.6.0
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.0
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  json_annotation: ^4.4.0
  intl: ^0.17.0
  awesome_dialog: ^2.1.2
  firebase_admin: ^0.2.0-dev.7
  firebase_messaging: ^13.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_hsvcolor_picker: ^1.2.2
  firebase_core: ^1.22.0
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_barcodes: ^20.1.61
  webview_flutter: ^3.0.4
  fluttertoast: ^8.0.9
  flutter_local_notifications: ^9.7.1
  flutterfire_cli: ^0.2.4
  
  #image_gallery_saver: ^1.7.0
  #image_picker: ^0.8.4
 # permission_handler: ^8.1.4
  

  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/M.png"  

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/lang/

    #Whiteicons

  
   
    - images/icons/iconsW/scssW.png
    - images/icons/iconsW/attW.png
    - images/icons/iconsW/lapW.png
    - images/icons/iconsW/no_attW.png
    - images/icons/iconsW/no_lapW.png
    - images/icons/iconsW/questW.png
    - images/icons/iconsW/quest2W.png
    - images/icons/iconsW/resultW.png
    - images/icons/iconsW/secW.png
    - images/icons/iconsW/sesW.png
    
  
    #Blackicons

  
   
    - images/icons/iconsB/scssB.png
    - images/icons/iconsB/attB.png
    - images/icons/iconsB/lapB.png
    - images/icons/iconsB/no_attB.png
    - images/icons/iconsB/no_lapB.png
    - images/icons/iconsB/questB.png
    - images/icons/iconsB/quest2B.png
    - images/icons/iconsB/resultB.png
    - images/icons/iconsB/secB.png
    - images/icons/iconsB/sesB.png
    

    #logos

    - images/logos/nnhhmm.jpg
    - images/logos/Facebook.png
    - images/logos/location.png
   
    - images/logos/NMW.png
    - images/logos/NMB.png
    - images/logos/NNHMMW.png
    - images/logos/NNHMMB.png



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
